// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: alarms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAlarmHistory = `-- name: CountAlarmHistory :one
SELECT count(*) 
FROM alarms a
WHERE (a.device_guid = $1 OR $1 IS NULL)
  AND (a.status = $2 OR $2 IS NULL)
  AND ($3::uuid IS NULL OR EXISTS (
      SELECT 1 FROM installation_points ip 
      WHERE ip.device_guid = a.device_guid 
        AND ip.location_guid = $3 
        AND ip.deleted_at IS NULL
  ))
  AND a.deleted_at IS NULL
`

type CountAlarmHistoryParams struct {
	DeviceGuid   pgtype.UUID     `json:"device_guid"`
	Status       NullAlarmStatus `json:"status"`
	LocationGuid pgtype.UUID     `json:"location_guid"`
}

func (q *Queries) CountAlarmHistory(ctx context.Context, arg CountAlarmHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAlarmHistory, arg.DeviceGuid, arg.Status, arg.LocationGuid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAlarmsByStatus = `-- name: CountAlarmsByStatus :many
SELECT status, count(*) as count
FROM alarms
WHERE (device_guid = $1 OR $1 IS NULL)
  AND deleted_at IS NULL
GROUP BY status
`

type CountAlarmsByStatusRow struct {
	Status AlarmStatus `json:"status"`
	Count  int64       `json:"count"`
}

func (q *Queries) CountAlarmsByStatus(ctx context.Context, deviceGuid pgtype.UUID) ([]CountAlarmsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countAlarmsByStatus, deviceGuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAlarmsByStatusRow{}
	for rows.Next() {
		var i CountAlarmsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAlarm = `-- name: CreateAlarm :one
INSERT INTO alarms (
    device_guid, threshold_guid, parameter_name, triggered_value, severity, status, triggered_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING guid, device_guid, threshold_guid, parameter_name, triggered_value, status, severity, triggered_at, resolved_at, acknowledged_at, acknowledged_by, created_at, updated_at, deleted_at
`

type CreateAlarmParams struct {
	DeviceGuid     pgtype.UUID        `json:"device_guid"`
	ThresholdGuid  pgtype.UUID        `json:"threshold_guid"`
	ParameterName  string             `json:"parameter_name"`
	TriggeredValue float64            `json:"triggered_value"`
	Severity       AlarmSeverity      `json:"severity"`
	Status         AlarmStatus        `json:"status"`
	TriggeredAt    pgtype.Timestamptz `json:"triggered_at"`
}

func (q *Queries) CreateAlarm(ctx context.Context, arg CreateAlarmParams) (Alarm, error) {
	row := q.db.QueryRow(ctx, createAlarm,
		arg.DeviceGuid,
		arg.ThresholdGuid,
		arg.ParameterName,
		arg.TriggeredValue,
		arg.Severity,
		arg.Status,
		arg.TriggeredAt,
	)
	var i Alarm
	err := row.Scan(
		&i.Guid,
		&i.DeviceGuid,
		&i.ThresholdGuid,
		&i.ParameterName,
		&i.TriggeredValue,
		&i.Status,
		&i.Severity,
		&i.TriggeredAt,
		&i.ResolvedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveAlarmByDeviceParam = `-- name: GetActiveAlarmByDeviceParam :one
SELECT guid, device_guid, threshold_guid, parameter_name, triggered_value, status, severity, triggered_at, resolved_at, acknowledged_at, acknowledged_by, created_at, updated_at, deleted_at FROM alarms
WHERE device_guid = $1 AND parameter_name = $2 AND status = 'active' AND deleted_at IS NULL
LIMIT 1
`

type GetActiveAlarmByDeviceParamParams struct {
	DeviceGuid    pgtype.UUID `json:"device_guid"`
	ParameterName string      `json:"parameter_name"`
}

func (q *Queries) GetActiveAlarmByDeviceParam(ctx context.Context, arg GetActiveAlarmByDeviceParamParams) (Alarm, error) {
	row := q.db.QueryRow(ctx, getActiveAlarmByDeviceParam, arg.DeviceGuid, arg.ParameterName)
	var i Alarm
	err := row.Scan(
		&i.Guid,
		&i.DeviceGuid,
		&i.ThresholdGuid,
		&i.ParameterName,
		&i.TriggeredValue,
		&i.Status,
		&i.Severity,
		&i.TriggeredAt,
		&i.ResolvedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAlarmByGUID = `-- name: GetAlarmByGUID :one
SELECT guid, device_guid, threshold_guid, parameter_name, triggered_value, status, severity, triggered_at, resolved_at, acknowledged_at, acknowledged_by, created_at, updated_at, deleted_at FROM alarms
WHERE guid = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetAlarmByGUID(ctx context.Context, guid pgtype.UUID) (Alarm, error) {
	row := q.db.QueryRow(ctx, getAlarmByGUID, guid)
	var i Alarm
	err := row.Scan(
		&i.Guid,
		&i.DeviceGuid,
		&i.ThresholdGuid,
		&i.ParameterName,
		&i.TriggeredValue,
		&i.Status,
		&i.Severity,
		&i.TriggeredAt,
		&i.ResolvedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveAlarmsByDevice = `-- name: ListActiveAlarmsByDevice :many
SELECT guid, device_guid, threshold_guid, parameter_name, triggered_value, status, severity, triggered_at, resolved_at, acknowledged_at, acknowledged_by, created_at, updated_at, deleted_at FROM alarms
WHERE device_guid = $1 AND status = 'active' AND deleted_at IS NULL
ORDER BY triggered_at DESC
`

func (q *Queries) ListActiveAlarmsByDevice(ctx context.Context, deviceGuid pgtype.UUID) ([]Alarm, error) {
	rows, err := q.db.Query(ctx, listActiveAlarmsByDevice, deviceGuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alarm{}
	for rows.Next() {
		var i Alarm
		if err := rows.Scan(
			&i.Guid,
			&i.DeviceGuid,
			&i.ThresholdGuid,
			&i.ParameterName,
			&i.TriggeredValue,
			&i.Status,
			&i.Severity,
			&i.TriggeredAt,
			&i.ResolvedAt,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlarmHistory = `-- name: ListAlarmHistory :many
SELECT 
    a.guid, a.device_guid, a.threshold_guid, a.parameter_name, a.triggered_value, a.status, a.severity, a.triggered_at, a.resolved_at, a.acknowledged_at, a.acknowledged_by, a.created_at, a.updated_at, a.deleted_at, 
    d.serial_number as device_sn, 
    d.alias as device_alias,
    COALESCE((SELECT l.name FROM installation_points ip 
      JOIN locations l ON ip.location_guid = l.guid 
      WHERE ip.device_guid = a.device_guid AND ip.deleted_at IS NULL 
      ORDER BY ip.created_at DESC LIMIT 1), '')::text as location_name
FROM alarms a
JOIN devices d ON a.device_guid = d.guid
WHERE (a.device_guid = $1 OR $1 IS NULL)
  AND (a.status = $2 OR $2 IS NULL)
  AND ($3::uuid IS NULL OR EXISTS (
      SELECT 1 FROM installation_points ip 
      WHERE ip.device_guid = a.device_guid 
        AND ip.location_guid = $3 
        AND ip.deleted_at IS NULL
  ))
  AND a.deleted_at IS NULL
ORDER BY a.triggered_at DESC
LIMIT $5 OFFSET $4
`

type ListAlarmHistoryParams struct {
	DeviceGuid   pgtype.UUID     `json:"device_guid"`
	Status       NullAlarmStatus `json:"status"`
	LocationGuid pgtype.UUID     `json:"location_guid"`
	Offset       int32           `json:"offset"`
	Limit        int32           `json:"limit"`
}

type ListAlarmHistoryRow struct {
	Guid           pgtype.UUID        `json:"guid"`
	DeviceGuid     pgtype.UUID        `json:"device_guid"`
	ThresholdGuid  pgtype.UUID        `json:"threshold_guid"`
	ParameterName  string             `json:"parameter_name"`
	TriggeredValue float64            `json:"triggered_value"`
	Status         AlarmStatus        `json:"status"`
	Severity       AlarmSeverity      `json:"severity"`
	TriggeredAt    pgtype.Timestamptz `json:"triggered_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	AcknowledgedBy pgtype.UUID        `json:"acknowledged_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	DeviceSn       string             `json:"device_sn"`
	DeviceAlias    pgtype.Text        `json:"device_alias"`
	LocationName   string             `json:"location_name"`
}

func (q *Queries) ListAlarmHistory(ctx context.Context, arg ListAlarmHistoryParams) ([]ListAlarmHistoryRow, error) {
	rows, err := q.db.Query(ctx, listAlarmHistory,
		arg.DeviceGuid,
		arg.Status,
		arg.LocationGuid,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlarmHistoryRow{}
	for rows.Next() {
		var i ListAlarmHistoryRow
		if err := rows.Scan(
			&i.Guid,
			&i.DeviceGuid,
			&i.ThresholdGuid,
			&i.ParameterName,
			&i.TriggeredValue,
			&i.Status,
			&i.Severity,
			&i.TriggeredAt,
			&i.ResolvedAt,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeviceSn,
			&i.DeviceAlias,
			&i.LocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlarmStatus = `-- name: UpdateAlarmStatus :one
UPDATE alarms
SET 
    status = $1::alarm_status,
    acknowledged_at = CASE WHEN $1::text = 'acknowledged' THEN NOW() ELSE acknowledged_at END,
    acknowledged_by = CASE WHEN $1::text = 'acknowledged' THEN $2 ELSE acknowledged_by END,
    resolved_at = CASE WHEN $1::text = 'resolved' THEN NOW() ELSE resolved_at END,
    updated_at = NOW()
WHERE guid = $3 AND deleted_at IS NULL
RETURNING guid, device_guid, threshold_guid, parameter_name, triggered_value, status, severity, triggered_at, resolved_at, acknowledged_at, acknowledged_by, created_at, updated_at, deleted_at
`

type UpdateAlarmStatusParams struct {
	Status         AlarmStatus `json:"status"`
	AcknowledgedBy pgtype.UUID `json:"acknowledged_by"`
	Guid           pgtype.UUID `json:"guid"`
}

func (q *Queries) UpdateAlarmStatus(ctx context.Context, arg UpdateAlarmStatusParams) (Alarm, error) {
	row := q.db.QueryRow(ctx, updateAlarmStatus, arg.Status, arg.AcknowledgedBy, arg.Guid)
	var i Alarm
	err := row.Scan(
		&i.Guid,
		&i.DeviceGuid,
		&i.ThresholdGuid,
		&i.ParameterName,
		&i.TriggeredValue,
		&i.Status,
		&i.Severity,
		&i.TriggeredAt,
		&i.ResolvedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
