// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: apikeys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAPIKeys = `-- name: CountAPIKeys :one
SELECT COUNT(*) FROM apikeys WHERE deleted_at IS NULL
`

func (q *Queries) CountAPIKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO apikeys (guid, key_hash, notes, expire_date, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAPIKeyParams struct {
	Guid       pgtype.UUID        `json:"guid"`
	KeyHash    string             `json:"key_hash"`
	Notes      pgtype.Text        `json:"notes"`
	ExpireDate pgtype.Timestamptz `json:"expire_date"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.Guid,
		arg.KeyHash,
		arg.Notes,
		arg.ExpireDate,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
UPDATE apikeys
SET deleted_at = $2, updated_at = $2
WHERE guid = $1 AND deleted_at IS NULL
`

type DeleteAPIKeyParams struct {
	Guid      pgtype.UUID        `json:"guid"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.Guid, arg.DeletedAt)
	return err
}

const getAPIKeyByGUID = `-- name: GetAPIKeyByGUID :one
SELECT guid, key_hash, notes, expire_date, is_active, created_at, updated_at, deleted_at
FROM apikeys
WHERE guid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAPIKeyByGUID(ctx context.Context, guid pgtype.UUID) (Apikey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByGUID, guid)
	var i Apikey
	err := row.Scan(
		&i.Guid,
		&i.KeyHash,
		&i.Notes,
		&i.ExpireDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAPIKeyByKeyHash = `-- name: GetAPIKeyByKeyHash :one
SELECT guid, key_hash, notes, expire_date, is_active, created_at, updated_at, deleted_at
FROM apikeys
WHERE key_hash = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAPIKeyByKeyHash(ctx context.Context, keyHash string) (Apikey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByKeyHash, keyHash)
	var i Apikey
	err := row.Scan(
		&i.Guid,
		&i.KeyHash,
		&i.Notes,
		&i.ExpireDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT guid, key_hash, notes, expire_date, is_active, created_at, updated_at, deleted_at
FROM apikeys
WHERE deleted_at IS NULL
  AND notes ILIKE $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAPIKeysParams struct {
	Notes  pgtype.Text `json:"notes"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]Apikey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, arg.Notes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Apikey{}
	for rows.Next() {
		var i Apikey
		if err := rows.Scan(
			&i.Guid,
			&i.KeyHash,
			&i.Notes,
			&i.ExpireDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKey = `-- name: UpdateAPIKey :exec
UPDATE apikeys
SET notes = $2, expire_date = $3, is_active = $4, updated_at = $5
WHERE guid = $1 AND deleted_at IS NULL
`

type UpdateAPIKeyParams struct {
	Guid       pgtype.UUID        `json:"guid"`
	Notes      pgtype.Text        `json:"notes"`
	ExpireDate pgtype.Timestamptz `json:"expire_date"`
	IsActive   bool               `json:"is_active"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, updateAPIKey,
		arg.Guid,
		arg.Notes,
		arg.ExpireDate,
		arg.IsActive,
		arg.UpdatedAt,
	)
	return err
}
