// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDevices = `-- name: CountDevices :one
SELECT COUNT(*) FROM devices WHERE deleted_at IS NULL
`

func (q *Queries) CountDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDevices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :exec
INSERT INTO devices (guid, type, serial_number, alias, notes, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateDeviceParams struct {
	Guid         pgtype.UUID        `json:"guid"`
	Type         string             `json:"type"`
	SerialNumber string             `json:"serial_number"`
	Alias        pgtype.Text        `json:"alias"`
	Notes        pgtype.Text        `json:"notes"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.Exec(ctx, createDevice,
		arg.Guid,
		arg.Type,
		arg.SerialNumber,
		arg.Alias,
		arg.Notes,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteDevice = `-- name: DeleteDevice :exec
UPDATE devices
SET deleted_at = $2, updated_at = $2
WHERE guid = $1 AND deleted_at IS NULL
`

type DeleteDeviceParams struct {
	Guid      pgtype.UUID        `json:"guid"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteDevice, arg.Guid, arg.DeletedAt)
	return err
}

const existsDeviceBySerialNumber = `-- name: ExistsDeviceBySerialNumber :one
SELECT EXISTS(SELECT 1 FROM devices WHERE serial_number = $1 AND deleted_at IS NULL)
`

func (q *Queries) ExistsDeviceBySerialNumber(ctx context.Context, serialNumber string) (bool, error) {
	row := q.db.QueryRow(ctx, existsDeviceBySerialNumber, serialNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDeviceByGUID = `-- name: GetDeviceByGUID :one
SELECT guid, type, serial_number, alias, notes, is_active, created_at, updated_at, deleted_at
FROM devices
WHERE guid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDeviceByGUID(ctx context.Context, guid pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByGUID, guid)
	var i Device
	err := row.Scan(
		&i.Guid,
		&i.Type,
		&i.SerialNumber,
		&i.Alias,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeviceBySerialNumber = `-- name: GetDeviceBySerialNumber :one
SELECT guid, type, serial_number, alias, notes, is_active, created_at, updated_at, deleted_at
FROM devices
WHERE serial_number = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDeviceBySerialNumber(ctx context.Context, serialNumber string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceBySerialNumber, serialNumber)
	var i Device
	err := row.Scan(
		&i.Guid,
		&i.Type,
		&i.SerialNumber,
		&i.Alias,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT guid, type, serial_number, alias, notes, is_active, created_at, updated_at, deleted_at
FROM devices
WHERE deleted_at IS NULL
  AND (serial_number ILIKE $1 OR alias ILIKE $1 OR type ILIKE $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDevicesParams struct {
	SerialNumber string `json:"serial_number"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices, arg.SerialNumber, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.Guid,
			&i.Type,
			&i.SerialNumber,
			&i.Alias,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :exec
UPDATE devices
SET type = $2, serial_number = $3, alias = $4, notes = $5, is_active = $6, updated_at = $7
WHERE guid = $1 AND deleted_at IS NULL
`

type UpdateDeviceParams struct {
	Guid         pgtype.UUID        `json:"guid"`
	Type         string             `json:"type"`
	SerialNumber string             `json:"serial_number"`
	Alias        pgtype.Text        `json:"alias"`
	Notes        pgtype.Text        `json:"notes"`
	IsActive     bool               `json:"is_active"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error {
	_, err := q.db.Exec(ctx, updateDevice,
		arg.Guid,
		arg.Type,
		arg.SerialNumber,
		arg.Alias,
		arg.Notes,
		arg.IsActive,
		arg.UpdatedAt,
	)
	return err
}
