// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: installation_points.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInstallationPoints = `-- name: CountInstallationPoints :one
SELECT COUNT(*) FROM installation_points WHERE deleted_at IS NULL
`

func (q *Queries) CountInstallationPoints(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInstallationPoints)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInstallationPoint = `-- name: CreateInstallationPoint :exec
INSERT INTO installation_points (guid, name, device_guid, location_guid, notes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateInstallationPointParams struct {
	Guid         pgtype.UUID        `json:"guid"`
	Name         string             `json:"name"`
	DeviceGuid   pgtype.UUID        `json:"device_guid"`
	LocationGuid pgtype.UUID        `json:"location_guid"`
	Notes        pgtype.Text        `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateInstallationPoint(ctx context.Context, arg CreateInstallationPointParams) error {
	_, err := q.db.Exec(ctx, createInstallationPoint,
		arg.Guid,
		arg.Name,
		arg.DeviceGuid,
		arg.LocationGuid,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteInstallationPoint = `-- name: DeleteInstallationPoint :exec
UPDATE installation_points
SET deleted_at = $2, updated_at = $2
WHERE guid = $1 AND deleted_at IS NULL
`

type DeleteInstallationPointParams struct {
	Guid      pgtype.UUID        `json:"guid"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) DeleteInstallationPoint(ctx context.Context, arg DeleteInstallationPointParams) error {
	_, err := q.db.Exec(ctx, deleteInstallationPoint, arg.Guid, arg.DeletedAt)
	return err
}

const getInstallationPointByGUID = `-- name: GetInstallationPointByGUID :one
SELECT guid, name, device_guid, location_guid, notes, created_at, updated_at, deleted_at
FROM installation_points
WHERE guid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInstallationPointByGUID(ctx context.Context, guid pgtype.UUID) (InstallationPoint, error) {
	row := q.db.QueryRow(ctx, getInstallationPointByGUID, guid)
	var i InstallationPoint
	err := row.Scan(
		&i.Guid,
		&i.Name,
		&i.DeviceGuid,
		&i.LocationGuid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInstallationPointWithRelations = `-- name: GetInstallationPointWithRelations :one
SELECT
    ip.guid, ip.name, ip.device_guid, ip.location_guid, ip.notes, ip.created_at, ip.updated_at, ip.deleted_at,
    d.serial_number, d.alias, l.name
FROM installation_points ip
LEFT JOIN devices d ON ip.device_guid = d.guid
LEFT JOIN locations l ON ip.location_guid = l.guid
WHERE ip.guid = $1 AND ip.deleted_at IS NULL
`

type GetInstallationPointWithRelationsRow struct {
	Guid         pgtype.UUID        `json:"guid"`
	Name         string             `json:"name"`
	DeviceGuid   pgtype.UUID        `json:"device_guid"`
	LocationGuid pgtype.UUID        `json:"location_guid"`
	Notes        pgtype.Text        `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	SerialNumber pgtype.Text        `json:"serial_number"`
	Alias        pgtype.Text        `json:"alias"`
	Name_2       pgtype.Text        `json:"name_2"`
}

func (q *Queries) GetInstallationPointWithRelations(ctx context.Context, guid pgtype.UUID) (GetInstallationPointWithRelationsRow, error) {
	row := q.db.QueryRow(ctx, getInstallationPointWithRelations, guid)
	var i GetInstallationPointWithRelationsRow
	err := row.Scan(
		&i.Guid,
		&i.Name,
		&i.DeviceGuid,
		&i.LocationGuid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SerialNumber,
		&i.Alias,
		&i.Name_2,
	)
	return i, err
}

const listInstallationPoints = `-- name: ListInstallationPoints :many
SELECT ip.guid, ip.name, ip.device_guid, ip.location_guid, ip.notes, ip.created_at, ip.updated_at, ip.deleted_at
FROM installation_points ip
WHERE ip.deleted_at IS NULL
  AND ($1::text IS NULL OR ip.name ILIKE $1 OR ip.notes ILIKE $1)
  AND ($2::uuid IS NULL OR ip.device_guid = $2)
  AND ($3::uuid IS NULL OR ip.location_guid = $3)
ORDER BY ip.created_at DESC
LIMIT $4 OFFSET $5
`

type ListInstallationPointsParams struct {
	Column1 string      `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
	Column3 pgtype.UUID `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListInstallationPoints(ctx context.Context, arg ListInstallationPointsParams) ([]InstallationPoint, error) {
	rows, err := q.db.Query(ctx, listInstallationPoints,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstallationPoint{}
	for rows.Next() {
		var i InstallationPoint
		if err := rows.Scan(
			&i.Guid,
			&i.Name,
			&i.DeviceGuid,
			&i.LocationGuid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstallationPoint = `-- name: UpdateInstallationPoint :exec
UPDATE installation_points
SET name = $2, device_guid = $3, location_guid = $4, notes = $5, updated_at = $6
WHERE guid = $1 AND deleted_at IS NULL
`

type UpdateInstallationPointParams struct {
	Guid         pgtype.UUID        `json:"guid"`
	Name         string             `json:"name"`
	DeviceGuid   pgtype.UUID        `json:"device_guid"`
	LocationGuid pgtype.UUID        `json:"location_guid"`
	Notes        pgtype.Text        `json:"notes"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateInstallationPoint(ctx context.Context, arg UpdateInstallationPointParams) error {
	_, err := q.db.Exec(ctx, updateInstallationPoint,
		arg.Guid,
		arg.Name,
		arg.DeviceGuid,
		arg.LocationGuid,
		arg.Notes,
		arg.UpdatedAt,
	)
	return err
}
