// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLocations = `-- name: CountLocations :one
SELECT COUNT(*) FROM locations WHERE deleted_at IS NULL
`

func (q *Queries) CountLocations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLocations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocation = `-- name: CreateLocation :exec
INSERT INTO locations (guid, name, notes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateLocationParams struct {
	Guid      pgtype.UUID        `json:"guid"`
	Name      string             `json:"name"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) error {
	_, err := q.db.Exec(ctx, createLocation,
		arg.Guid,
		arg.Name,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteLocation = `-- name: DeleteLocation :exec
UPDATE locations
SET deleted_at = $2, updated_at = $2
WHERE guid = $1 AND deleted_at IS NULL
`

type DeleteLocationParams struct {
	Guid      pgtype.UUID        `json:"guid"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) DeleteLocation(ctx context.Context, arg DeleteLocationParams) error {
	_, err := q.db.Exec(ctx, deleteLocation, arg.Guid, arg.DeletedAt)
	return err
}

const existsLocationByName = `-- name: ExistsLocationByName :one
SELECT EXISTS(SELECT 1 FROM locations WHERE name = $1 AND deleted_at IS NULL)
`

func (q *Queries) ExistsLocationByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, existsLocationByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getLocationByGUID = `-- name: GetLocationByGUID :one
SELECT guid, name, notes, created_at, updated_at, deleted_at
FROM locations
WHERE guid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLocationByGUID(ctx context.Context, guid pgtype.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByGUID, guid)
	var i Location
	err := row.Scan(
		&i.Guid,
		&i.Name,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT guid, name, notes, created_at, updated_at, deleted_at
FROM locations
WHERE deleted_at IS NULL
  AND (name ILIKE $1 OR notes ILIKE $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLocationsParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.Guid,
			&i.Name,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :exec
UPDATE locations
SET name = $2, notes = $3, updated_at = $4
WHERE guid = $1 AND deleted_at IS NULL
`

type UpdateLocationParams struct {
	Guid      pgtype.UUID        `json:"guid"`
	Name      string             `json:"name"`
	Notes     pgtype.Text        `json:"notes"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) error {
	_, err := q.db.Exec(ctx, updateLocation,
		arg.Guid,
		arg.Name,
		arg.Notes,
		arg.UpdatedAt,
	)
	return err
}
