// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Apikey struct {
	Guid       pgtype.UUID        `json:"guid"`
	KeyHash    string             `json:"key_hash"`
	Notes      pgtype.Text        `json:"notes"`
	ExpireDate pgtype.Timestamptz `json:"expire_date"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Device struct {
	Guid         pgtype.UUID        `json:"guid"`
	Type         string             `json:"type"`
	SerialNumber string             `json:"serial_number"`
	Alias        pgtype.Text        `json:"alias"`
	Notes        pgtype.Text        `json:"notes"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type InstallationPoint struct {
	Guid         pgtype.UUID        `json:"guid"`
	Name         string             `json:"name"`
	DeviceGuid   pgtype.UUID        `json:"device_guid"`
	LocationGuid pgtype.UUID        `json:"location_guid"`
	Notes        pgtype.Text        `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Location struct {
	Guid      pgtype.UUID        `json:"guid"`
	Name      string             `json:"name"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type RefreshToken struct {
	Guid      pgtype.UUID        `json:"guid"`
	UserGuid  pgtype.UUID        `json:"user_guid"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	Guid         pgtype.UUID        `json:"guid"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	RoleGuid     pgtype.UUID        `json:"role_guid"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
