// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (guid, user_guid, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	Guid      pgtype.UUID        `json:"guid"`
	UserGuid  pgtype.UUID        `json:"user_guid"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.Guid,
		arg.UserGuid,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, expiresAt)
	return err
}

const deleteRefreshTokenByTokenHash = `-- name: DeleteRefreshTokenByTokenHash :exec
DELETE FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshTokenByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByTokenHash, tokenHash)
	return err
}

const deleteRefreshTokensByUserGUID = `-- name: DeleteRefreshTokensByUserGUID :exec
DELETE FROM refresh_tokens WHERE user_guid = $1
`

func (q *Queries) DeleteRefreshTokensByUserGUID(ctx context.Context, userGuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUserGUID, userGuid)
	return err
}

const getRefreshTokenByTokenHash = `-- name: GetRefreshTokenByTokenHash :one
SELECT guid, user_guid, token_hash, expires_at, created_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByTokenHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByTokenHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.Guid,
		&i.UserGuid,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
