// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: thresholds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createThreshold = `-- name: CreateThreshold :one
INSERT INTO thresholds (
    device_guid, parameter_name, min_value, max_value, severity, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING guid, device_guid, parameter_name, min_value, max_value, severity, is_active, created_at, updated_at, deleted_at
`

type CreateThresholdParams struct {
	DeviceGuid    pgtype.UUID   `json:"device_guid"`
	ParameterName string        `json:"parameter_name"`
	MinValue      pgtype.Float8 `json:"min_value"`
	MaxValue      pgtype.Float8 `json:"max_value"`
	Severity      AlarmSeverity `json:"severity"`
	IsActive      bool          `json:"is_active"`
}

func (q *Queries) CreateThreshold(ctx context.Context, arg CreateThresholdParams) (Threshold, error) {
	row := q.db.QueryRow(ctx, createThreshold,
		arg.DeviceGuid,
		arg.ParameterName,
		arg.MinValue,
		arg.MaxValue,
		arg.Severity,
		arg.IsActive,
	)
	var i Threshold
	err := row.Scan(
		&i.Guid,
		&i.DeviceGuid,
		&i.ParameterName,
		&i.MinValue,
		&i.MaxValue,
		&i.Severity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteThreshold = `-- name: DeleteThreshold :exec
UPDATE thresholds
SET deleted_at = NOW()
WHERE guid = $1
`

func (q *Queries) DeleteThreshold(ctx context.Context, guid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteThreshold, guid)
	return err
}

const getThresholdByGUID = `-- name: GetThresholdByGUID :one
SELECT guid, device_guid, parameter_name, min_value, max_value, severity, is_active, created_at, updated_at, deleted_at FROM thresholds
WHERE guid = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetThresholdByGUID(ctx context.Context, guid pgtype.UUID) (Threshold, error) {
	row := q.db.QueryRow(ctx, getThresholdByGUID, guid)
	var i Threshold
	err := row.Scan(
		&i.Guid,
		&i.DeviceGuid,
		&i.ParameterName,
		&i.MinValue,
		&i.MaxValue,
		&i.Severity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listThresholdsByDevice = `-- name: ListThresholdsByDevice :many
SELECT guid, device_guid, parameter_name, min_value, max_value, severity, is_active, created_at, updated_at, deleted_at FROM thresholds
WHERE device_guid = $1 AND deleted_at IS NULL
ORDER BY parameter_name ASC
`

func (q *Queries) ListThresholdsByDevice(ctx context.Context, deviceGuid pgtype.UUID) ([]Threshold, error) {
	rows, err := q.db.Query(ctx, listThresholdsByDevice, deviceGuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Threshold{}
	for rows.Next() {
		var i Threshold
		if err := rows.Scan(
			&i.Guid,
			&i.DeviceGuid,
			&i.ParameterName,
			&i.MinValue,
			&i.MaxValue,
			&i.Severity,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThreshold = `-- name: UpdateThreshold :one
UPDATE thresholds
SET 
    parameter_name = $2,
    min_value = $3,
    max_value = $4,
    severity = $5,
    is_active = $6,
    updated_at = NOW()
WHERE guid = $1 AND deleted_at IS NULL
RETURNING guid, device_guid, parameter_name, min_value, max_value, severity, is_active, created_at, updated_at, deleted_at
`

type UpdateThresholdParams struct {
	Guid          pgtype.UUID   `json:"guid"`
	ParameterName string        `json:"parameter_name"`
	MinValue      pgtype.Float8 `json:"min_value"`
	MaxValue      pgtype.Float8 `json:"max_value"`
	Severity      AlarmSeverity `json:"severity"`
	IsActive      bool          `json:"is_active"`
}

func (q *Queries) UpdateThreshold(ctx context.Context, arg UpdateThresholdParams) (Threshold, error) {
	row := q.db.QueryRow(ctx, updateThreshold,
		arg.Guid,
		arg.ParameterName,
		arg.MinValue,
		arg.MaxValue,
		arg.Severity,
		arg.IsActive,
	)
	var i Threshold
	err := row.Scan(
		&i.Guid,
		&i.DeviceGuid,
		&i.ParameterName,
		&i.MinValue,
		&i.MaxValue,
		&i.Severity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
